//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apples_To_Apples
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ApplesToApplesDBEntities : DbContext
    {
        public ApplesToApplesDBEntities()
            : base("name=ApplesToApplesDBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<GameInfo> GameInfo { get; set; }
        public virtual DbSet<GreenDeckOfCard> GreenDeckOfCards { get; set; }
        public virtual DbSet<PlayerInfo> PlayerInfo { get; set; }
        public virtual DbSet<RedDeckOfCard> RedDeckOfCards { get; set; }
        public virtual DbSet<RoundInfo> RoundInfo { get; set; }
        public virtual DbSet<UseDeck> UseDeck { get; set; }
        public virtual DbSet<UserLogin> UserLogin { get; set; }
    }
}
